"""empty message

Revision ID: 416fd39601fb
Revises: 145691cda49e
Create Date: 2013-09-30 16:35:53.430341

"""

# revision identifiers, used by Alembic.
revision = '416fd39601fb'
down_revision = '145691cda49e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('owner_id', sa.String(length=36)))
    op.add_column('pages', sa.Column('team_id', sa.Integer()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'team_id')
    op.drop_column('pages', 'owner_id')
    ### end Alembic commands ###
